### ISSUE TITLE
ExcludeFromOutput only works for one property in class

### ISSUE THREAD

**Issue by rocjoe** [bradwestness/EPPlusEnumerable#12]
I.e. applying `[SpreadsheetTabName(ExcludeFromOutput = true)]` to more than one property in the same class, only one property will be excluded from the spreadsheet.

Based on other experiments, I understand now that  `SpreadsheetTabName` is only meant to be used once per class; but it's the only option that excludes columns from the results, which led me to posting this issue.

How about a new attribute: `[SpreadsheetIgnore]`?

**Comment by bradwestness** [comment]
Hi @rocjoe,

Thanks for the suggestion! My thinking is that if you don't want to include all the data, you would just make a new type that has only the fields you want, you could then select into the new type using LINQ or else use something like AutoMapper to map your data into the correct format you want *before* you send it to EPPlusEnumerable.

I can see the argument for using an attribute -- it prevents you from having to define a secondary type which is the same except for having a couple parameters taken out -- but at the same time it'd be easy for EPPlusEnumerable to get unwieldy really quickly by polluting your project with a million single-purpose attributes, and by extension making the EPPlusEnumerable code more complex and slower.

Does that sound reasonable?

**Comment by rocjoe** [comment]
Totally reasonable. KISS > convenience.

**Comment by mgpeter** [comment]
@bradwestness Hi! I'm new here. Just recently I encountered a situation when having an exclude attribute would be beneficial. I understand your case here, but imho, it's worth thinking through a scenario in which format of the exported data is unknown compile-time and the concrete type is emitted at runtime based on some configuration. I'm dealing with such a system now and having a possibility to just emit [SpreadsheetExcludeFromOutput] would be really a life saver there, cause we are not able to use LINQ nor AutoMapper to map the types easily without introducing several risks to the software while implementing custom reflection logic to delete properties not needed in output.

I forked the repository, and created a pull request to review this concept and small improvements in code. Obviously, this might need tuning further on to adjust my quick draft to proper style and coding guidelines. For now I'd greatly appreciate if you could spend just a few minutes to review the code to decide if we are on the same page here, if my changes do not conform to your plans, just let me know, cause I'm happy to help with other things for some time if that's fine for you.

I'm using VS 2015 so if you would like to merge the changes I might need to adjust the pull request a little to restore original nuget.exe and revert the sln changes, unless you want to start using VS 2015 further on.

Mentioned PR: #13

**Comment by bradwestness** [comment]
I'm confused. If you are emitting the types at runtime, can't you just not emit the field you don't want in the spreadsheet rather than including it but also emitting an attribute saying to exclude it?

**Comment by mgpeter** [comment]
@bradwestness it's a somewhat bigger customer-developed enterprise solution. We would need to duplicate the code a little to grab types and classes they emit based on some interfaces provided in code used for configuration. We are using the exclude attribute on base interfaces as we have limited to no access to the emit logic, which handles plenty of workflows before actually providing the final assembly. The other reason is performance overhead coming along another assembly generation process.

The issue here is: I understand that ideally we we would just provide properly schemed objects to EPPlusEnumerable, but sometimes it's just not feasible due to the project scope or other requirements when we have no direct control over everything in the code.

**Comment by bradwestness** [comment]
The 1.4.0.0 release now includes a SpreadsheetExcludeAttribute which can be used on one or more properties on a class to omit those from output in the generated spreadsheet. Note that as part of this change I also removed the ExcludeFromOutput property from the SpreadsheetTabNameAttribute as the same effect can be made by combining the SpreadsheetTabNameAttribute and SpreadsheetExcludeAttribute on a given property.
