### ISSUE TITLE
Types with IEnumerable properties

### ISSUE THREAD

**Issue by MohadKamil** [bradwestness/EPPlusEnumerable#14]
I have a scenario in which I want to generate a excel sheet for a list of object of a certain type, this type itself contains properties that are of type IEnumerable , the create method works fine for basic types , but outputs the number of elements in the enumerable properties .

**Comment by bradwestness** [comment]
Yes, that is the current intended behavior. Enumerable properties will receive a count in the output. What would you expect the spreadsheet cell to contain for an enumerble property?
