### ISSUE TITLE
referencing newer EPPlus

### ISSUE THREAD

**Issue by ce-billw** [bradwestness/EPPlusEnumerable#15]
Using EPPlus 4.0.5 and EPPlusEnumerable 1.4.0 (retrieved from NuGet) I'm getting the error message:  "Could not load file or assembly 'EPPlus, Version=4.0.4.0, Culture=neutral, PublicKeyToken=ea159fdaa78159a1' or one of its dependencies. The system cannot find the file specified."
I think the fix is to set "Specific Version" to false in your EPPlus reference.

**Comment by bradwestness** [comment]
Good catch. I just updated the NuGet package so it should now just work with 4.0 and up.
