### ISSUE TITLE
Excel Formatting for Large fields.

### ISSUE THREAD

**Issue by sharmanoopur15** [bradwestness/EPPlusEnumerable#17]
how to take care formatting the values after installing this libraries? My spreadsheet have some large fields  ,how to make wrap text true and set the alignments of those fields?

**Comment by bradwestness** [comment]
There is no way to do that currently, but those are good enhancement suggestions!

**Comment by bradwestness** [comment]
I'm building this out right now... are there any other options you'd find useful aside from text wrap and alignment? My intent is not to fully implement every possibility that exists if you're using EPPlus directly, but just to offer a subset of the most useful options.
