### ISSUE TITLE
Does not check MetadataType for attributes

### ISSUE THREAD

**Issue by aricept** [bradwestness/EPPlusEnumerable#18]
When using a MetadataType to store class attributes (useful when you cannot add them directly to the class, or when using EF Database-First classes which will regenerate when updates are made to the database model) EPPlusEnumerable does not see the attributes, as they are not on the class it is searching for attributes.

I've worked up an additional extension method that can be called from the existing `GetCustomAttribute` methods if no attributes are found; it requires that the Type also be passed to the `GetCustomAttribute` methods, but the code already has variables for the types in `collectionType`. 

I've also worked up a a sample MetadataType class that can be added to the SampleConsoleApp, and similar can be done for a unit test. I have everything except the unit test ready to go, and can submit a pull request.

**Comment by bradwestness** [comment]
Sounds great!
